export enum Models {
  PROFILE = 'Profile',
  USER = 'User',
  USER_STATISTIC = 'UserStatistic',
  CATEGORY = 'Category',
  CATEGORY_TRANSLATION = 'CategoryTranslation',
  ORDER = 'Order',
  PROFILE_STATISTIC = 'ProfileStatistic',
  ORDER_STATISTIC = 'OrderStatistic',
  FEEDBACK = 'Feedback',
  PROFILE_TRANSLATION = 'ProfileTranslation',
  PROFILE_RATING = 'ProfileRating',
  EXPORT_DATA = 'ExportData',
  NOTIFICATION = 'Notification',
  CATEGORY_TAGS = 'CategoryTags',
  CHAT_MESSAGE = 'ChatMessage',
  CHAT = 'Chat',
}
