export const notificationData = {
  items: [
    {
      id: 1,
      name: "Notification 1",
      date: "2021-10-10",
      page: "main",
      geography: "Ukraine",
      look: "banner",
    },
    {
      id: 2,
      name: "Notification 2",
      date: "2021-11-05",
      page: "secondary",
      geography: "United States",
      look: "modal",
    },
    {
      id: 3,
      name: "Notification 3",
      date: "2021-12-20",
      page: "main",
      geography: "Germany",
      look: "banner",
    },
    {
      id: 4,
      name: "Notification 4",
      date: "2022-01-15",
      page: "secondary",
      geography: "Canada",
      look: "modal",
    },
    {
      id: 5,
      name: "Notification 5",
      date: "2022-02-28",
      page: "main",
      geography: "Australia",
      look: "banner",
    },
    {
      id: 6,
      name: "Notification 6",
      date: "2022-03-10",
      page: "secondary",
      geography: "Brazil",
      look: "modal",
    },
    {
      id: 7,
      name: "Notification 7",
      date: "2022-04-05",
      page: "main",
      geography: "India",
      look: "banner",
    },
    {
      id: 8,
      name: "Notification 8",
      date: "2022-05-20",
      page: "secondary",
      geography: "Japan",
      look: "modal",
    },
    {
      id: 9,
      name: "Notification 9",
      date: "2022-06-15",
      page: "main",
      geography: "Mexico",
      look: "banner",
    },
    {
      id: 10,
      name: "Notification 10",
      date: "2022-07-30",
      page: "secondary",
      geography: "France",
      look: "modal",
    },
  ],
};
