FROM node:18-alpine

ARG NEXT_PUBLIC_ENV_TARGET
ARG NEXT_PUBLIC_TELEGRAM_BOT_NAME
ARG NEXT_PUBLIC_PLACES_API_KEY
ARG NEXT_PUBLIC_API_URL

WORKDIR /app

ENV NEXT_PUBLIC_ENV_TARGET=$NEXT_PUBLIC_ENV_TARGET
ENV NEXT_PUBLIC_TELEGRAM_BOT_NAME=$NEXT_PUBLIC_TELEGRAM_BOT_NAME
ENV NEXT_PUBLIC_PLACES_API_KEY=$NEXT_PUBLIC_PLACES_API_KEY
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY . .

RUN npm i
RUN npm run build

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]